apiVersion: v2
name: csi-wekafsplugin
description: Helm chart for Deployment of WekaIO Container Storage Interface (CSI) plugin for WekaFS - the world fastest filesystem
maintainers:
  - name: WekaIO, Inc.
    email: csi@weka.io
    url: https://weka.io
sources:
  - https://github.com/weka/csi-wekafs/tree/v$CHART_VERSION/deploy/helm/csi-wekafsplugin
home: https://github.com/weka/csi-wekafs
icon: https://weka.github.io/csi-wekafs/logo.png
type: application
version: 0.9.0-SNAPSHOT.87.4ecdb2b
appVersion: v0.9.0-SNAPSHOT.87.4ecdb2b
kubeVersion: ">=1.18.0"
