kind: Service
apiVersion: v1
metadata:
  name: csi-wekafs-provisioner
  labels:
    app: csi-wekafs-provisioner
spec:
  selector:
    app: csi-wekafs-provisioner
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-wekafs-provisioner
spec:
  serviceName: "csi-wekafs-provisioner"
  replicas: 1
  selector:
    matchLabels:
      app: csi-wekafs-provisioner
  template:
    metadata:
      labels:
        app: csi-wekafs-provisioner
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-wekafsplugin
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-provisioner
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.6.0
          args:
            - -v=5
            - --csi-address=/csi/csi.sock
            - --feature-gates=Topology=true
          securityContext:
            # This is necessary only for systems with SELinux, where
            # non-privileged sidecar containers cannot access unix domain socket
            # created by privileged CSI driver container.
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi-wekafs
            type: DirectoryOrCreate
          name: socket-dir
