apiVersion: v2
name: csi-wekafsplugin
description: Helm chart for Deployment of WekaIO Container Storage Interface (CSI) plugin for WekaFS - the world fastest filesystem
maintainers:
  - name: WekaIO, Inc.
    email: csi@weka.io
    url: https://weka.io
sources:
  - https://github.com/weka/csi-wekafs/tree/v2.1.0
home: https://github.com/weka/csi-wekafs
icon: https://weka.github.io/csi-wekafs/logo.png
type: application
version: 2.1.0
appVersion: v2.1.0
kubeVersion: ">=1.18.0"
keywords: [storage, filesystem, HPC]
annotations:
  artifacthub.io/category: "storage"
  artifacthub.io/prerelease: "false"
  artifacthub.io/containsSecurityUpdates: "true"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/signKey: |
    fingerprint: BA9F2D31BE9193E01FA17450BCE0A5CF67AC0C59
    url: https://weka.github.io/csi-wekafs/csi-public.gpg
