apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: wekafs.csi.k8s.io
spec:
  # Supports persistent volumes.
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
  # To determine at runtime which mode a volume uses, pod info and its
  # "csi.storage.k8s.io/ephemeral" entry are needed.
  podInfoOnMount: true
